# Site settings
baseurl = "https://shivamdixit.com/"
languageCode = "en"
title = "Shivam Dixit"
theme = "hugo-theme-cactus-plus"

publishDir = "docs"

googleAnalytics = "UA-47304954-1"

# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = false

[params]
    author = "Shivam Dixit"
    description = "Senior Software Engineer at Databricks, making Databricks’s systems more secure and reliable."
    bio = "Security | Reliability | Engineering"

    twitter = "shivamd001"

    enableRSS = true
    enableToc = false

    enableDisqus = true
    disqusShortname = "shivamdixit"

    enableSummary = true
    # Set the value to true if use description in post front matter replace content summary
    useDescriptionReplaceSummary = false


    enableGoogleAnalytics = true

    enableBaiduAnalytics = false
    # Set the value to your baidu analysis code if you want to use baidu analytics
    baiduAnalytics = 'your_baidu_analysis_code'

    enableTwitterCard = true
    # The url for twitter card image, default is avatar.png in static/images directory
    twitterCardImage = ""

    # Add custom assets with their paths relative to the static folder
    customCSS = ["css/main.css"]
    customJS  = []

    # The variables below are optionally too and can be used to
    # translate or customize each string of the theme.

    # Navigation links
    home = ""
    about = ""
    archive = ""
    categories = ""
    subscribe = "RSS"

    olderPosts = ""
    newerPosts = ""
    copyright = ""


    # show latest posts in single page
    showLatestPosts = false
    readMore = ""

    # Share
    enableShare = true
    tweet = ""
    share = ""

    # 404 page
    title404 = ""
    subtitle404 = ""

    # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
    iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = ""


# Add additional social link entries underneath
[social]
    twitter-square = "https://www.twitter.com/shivamd001"
    github-square = "https://www.github.com/shivamdixit"
    linkedin-square = "https://www.linkedin.com/in/shivamd001/"

[permalinks]
    posts = "/:slug/:filename/"
